language: node_js
sudo: false
node_js:
  - 6.0
  - 8.0
  - 10
cache: yarn
install: npm install
script:
- npm run lint
- npm run test
deploy:
  provider: npm
  email: julien.croain@gmail.com
  skip_cleanup: true
  api_key:
    secure: $NPM_SECURE_TOKEN
  on:
    tags: true
    repo: JulienCroain/vsix-info
    branch: master